@SuppressWarnings({ "requires-automatic"})
module dev.inward.matrix {
    requires transitive java.instrument;
    requires transitive java.sql;
    requires transitive org.objectweb.asm;
    requires transitive jdk.security.auth;
    requires jsr305;
    requires annotations;
    requires java.management;
    requires org.checkerframework.checker.qual;
    exports dev.inward.matrix.route;
    exports dev.inward.matrix.personality;
    exports dev.inward.matrix.ticket;
    exports dev.inward.matrix.concept.catalog;
    exports dev.inward.matrix.concept.fact.addressed.dns.nameServerRecord;
    exports dev.inward.matrix.concept.fact.addressed.depot;
    exports dev.inward.matrix.concept.fact.addressed.dns;
    exports dev.inward.matrix.item.datum.log;
    exports dev.inward.matrix.item.datum.administrator;
    exports dev.inward.matrix.executable;
    exports dev.inward.matrix.concept.fact.addressed.http;
    exports dev.inward.matrix.concept.fact.addressed.https;
    exports dev.inward.matrix.concept.fact.addressed.ldap;
    exports dev.inward.matrix.item.datum.indica;
    exports dev.inward.matrix.concept.fact.addressed;
    exports dev.inward.matrix.concept.fact;
    exports dev.inward.matrix.item.datum.standard;
    exports dev.inward.matrix.item.datum.source;
    exports dev.inward.matrix.item.datum.specification;
    exports dev.inward.matrix.concept.fact.addressed.dns.catalogRecord;
    exports dev.inward.matrix.concept.fact.addressed.dns.serverRecord;
    exports dev.inward.matrix.concept.fact.addressed.dns.serviceLocationRecord;
    exports dev.inward.matrix.concept.fact.addressed.dns.startOfAuthority;
    exports dev.inward.matrix.control;
    exports dev.inward.matrix.control.library;
    exports dev.inward.matrix.control.authority;
    exports dev.inward.matrix.control.domain;
    exports dev.inward.matrix.control.administration;
    exports dev.inward.matrix.control.scheme;
    exports dev.inward.matrix.concept.fact.directory;
    exports dev.inward.matrix.item;
    exports dev.inward.matrix.item.datum;
    exports dev.inward.matrix;
    exports dev.inward.matrix.control.terrene;
    exports dev.inward.matrix.concept;
    exports dev.inward.matrix.control.administration.platform;
    exports dev.inward.matrix.engine;
}