@SuppressWarnings({ "requires-automatic"})
module dev.inward.matrix {
    requires transitive java.instrument;
    requires transitive java.sql;
    requires transitive org.objectweb.asm;
    requires transitive jdk.security.auth;
    requires kotlin.stdlib;
    requires jsr305;
    requires annotations;
    requires java.management;
    exports dev.inward.matrix.engine;
    exports dev.inward.matrix.route;
    exports dev.inward.matrix.personality;
    exports dev.inward.matrix.ticket;
    exports dev.inward.matrix.concept.catalog;
    exports dev.inward.matrix.concept.file.addressed.dns.nameServerRecord;
    exports dev.inward.matrix.concept.file.addressed.depot;
    exports dev.inward.matrix.concept.file.addressed.dns;
    exports dev.inward.matrix.concept.file.addressed.log;
    exports dev.inward.matrix.concept.item.datum.administrator;
    exports dev.inward.matrix.predictable;
    exports dev.inward.matrix.concept.file.addressed.http;
    exports dev.inward.matrix.concept.file.addressed.depot.indica;
    exports dev.inward.matrix.concept.file.addressed;
    exports dev.inward.matrix.concept.file;
    exports dev.inward.matrix.concept.file.addressed.depot.standard;
    exports dev.inward.matrix.concept.file.addressed.depot.source;
    exports dev.inward.matrix.concept.file.addressed.depot.specification;
    exports dev.inward.matrix.concept.file.addressed.dns.catalogRecord;
    exports dev.inward.matrix.concept.file.addressed.dns.serverRecord;
    exports dev.inward.matrix.concept.file.addressed.dns.serviceLocationRecord;
    exports dev.inward.matrix.concept.file.addressed.dns.startOfAuthority;
    exports dev.inward.matrix.control;
    exports dev.inward.matrix.control.library;
    exports dev.inward.matrix.control.authority;
    exports dev.inward.matrix.control.domain;
    exports dev.inward.matrix.control.administration;
    exports dev.inward.matrix.control.scheme;
    exports dev.inward.matrix.concept.file.directory;
    exports dev.inward.matrix.concept.item;
    exports dev.inward.matrix.concept.item.datum;
    exports dev.inward.matrix;
    exports dev.inward.matrix.dns;
    exports dev.inward.matrix.control.terrene;
    exports dev.inward.matrix.concept;
}